version: '2'
services:
  php:
    command: ["sh", "-c", "apt update; apt install -y jq curl; php-fpm"]
    container_name: php-fpm
    image: php:fpm
    volumes:
      - ../www:/var/www/html/site
      - ../slidocli:/usr/local/bin/slidocli
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ../www:/var/www/html/site
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
