version: '2.1'
services:
  php:
    command: ["sh", "-c", "apt update; apt install -y jq curl; php-fpm"]
    container_name: php-fpm
    image: php:fpm
    volumes:
      - ../${SLIDO_WWW:-www1}:/var/www/html/site
      - ../slidocli:/usr/local/bin/slidocli
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ../${SLIDO_WWW:-www1}:/var/www/html/site
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${SLIDO_PORT:-8080}:80
